### PR TITLE
udp client + server

### PR DESCRIPTION
**Pull request by stuarth**
first cut at adding udp. what do we think?

### CODE REVIEW

**Comment by heyLu** [comment]
Thanks for working on this!

Could we have an interface that's similar to the tcp one?  In particular, I like that it returns a stream that you can read from and write to.

**Comment by halgari** [comment]
Does a stream make sense with a message based protocol like UDP?

**Comment by heyLu** [comment]
Apparently, not so much.  The last time I looked I *thought* various languages provided stream-like APIs to UDP.  Some do, but they all *also* provide a packet/message oriented API, which is likely the preferred one.

Not sure what the API should look like in Pixie, though.

(Examples: [Ruby][], [Go][], [Java][])

[Ruby]: http://ruby-doc.org/stdlib-1.9.3/libdoc/socket/rdoc/UDPSocket.html
[Go]: https://golang.org/pkg/net/#UDPConn
[Java]: https://docs.oracle.com/javase/8/docs/api/java/net/DatagramSocket.html

**Comment by stuarth** [comment]
Closing until I have a chance to revisit. Fair game for anyone to reopen + rework :)

**Pull request closed without merging**
