### PR TITLE
implement pixie.io/line-seq and pixie.io/read-line

### PR DESCRIPTION
**Pull request by kgann**
This adds `read-line` to the `IInputStream` protocol and implements `line-seq`

https://github.com/pixie-lang/pixie/issues/180

### CODE REVIEW

**Comment by heyLu** [comment]
Nice!

One nitpick/question: Why is `read-line` a new method on `IInputStream`, couldn't it be just a function that takes an `IInputStream` and returns the line?

**Comment by kgann** [comment]
You're correct, it could just be a function. Would you prefer this?

**Comment by heyLu** [comment]
Yes, because when someone writes a `TCPInputStream` or similar that implements `IInputStream` we can reuse `read-line`. :)

**Comment by kgann** [comment]
Great point. See 1849c62b2271a608f07020f10dfde1a023782275

**Comment by thomasmulvaney** [comment]
You could create a `IRead` protocol which extends `IInputStream`

So you could have:
```
(defprotocol IRead
   (read-line [])
   (read-string [])
   (read-sexp []))

(extend-protocol IRead
   IInputStream
   (read-line []
       ;; Implementation... )
   
   String
   (read-line [] ...)
   ...)
```
This might make sense if people want to `read-line` from things which don't implement `IInputStream`.

**Pull request merged**
