### PR TITLE
Add sequence to stdlib

### PR DESCRIPTION
**Pull request by angusiguess**
Implement sequence as per #502.

### CODE REVIEW

**Comment by thomasmulvaney** [comment]
Thanks for working on this. Would you be able to add some tests please?

**Comment by angusiguess** [comment]
Sure thing. While I was testing I noticed that eductions break the seqable contract in the empty case.

We'd expect:
```(seq (eduction (map inc) '[]))``` to produce nil

but it produces ```[]```

Calling seq on the result of the reduce seems to resolve this.

**Comment by thomasmulvaney** [comment]
I think the problem is that the `-seq` implementation on `Eduction` just does a reduce rather than returning a `LazySeq`. I think the best thing to do would be to fix that by making it lazy.

**Comment by angusiguess** [comment]
Agreed, I'll take a crack at it.

**Comment by angusiguess** [comment]
So I inverted things a little bit by making ```sequence``` work lazily and eduction make use of ```sequence```

**Comment by thomasmulvaney** [comment]
Thanks for working on this!

**Pull request merged**
