### PR TITLE
Adding a few missing trig functions.

### PR DESCRIPTION
**Pull request by cgore**

### CODE REVIEW

**Comment by cgore** [comment]
I'm not sure why a build didn't happen for this PR, can someone kick off a build?

**Comment by heyLu** [comment]
I'm not sure either.  I had a look [on travis](https://travis-ci.org/pixie-lang/pixie/pull_requests), but this pull request doesn't appear there.

Can you push to this branch again (`git commit --amend` + a force push would work) and see if it works then?  If it doesn't, maybe try creating a new PR with the same changes.

**Comment by cgore** [comment]
That seems to have kicked it off.

**Comment by cgore** [comment]
That's a weird error message, and I don't get that when I build it on my mac.

**Comment by heyLu** [comment]
I get it after a `make clean` on linux.

**Comment by heyLu** [comment]
The following patch "fixes" it, but I'm not sure if the other two JitDrivers (in `persistent_vector.py` and `stdlib.py`) need the `is_recursive` attribute as well.

```diff
diff --git a/pixie/vm/interpreter.py b/pixie/vm/interpreter.py
index 83e873d..d279e2f 100644
--- a/pixie/vm/interpreter.py
+++ b/pixie/vm/interpreter.py
@@ -11,7 +11,7 @@ def get_location(ip, sp, is_continuation, bc, base_code):
     return code.BYTECODES[bc[ip]] + " in " + str(base_code._name)
 
 jitdriver = JitDriver(greens=["ip", "sp", "is_continuation", "bc", "base_code"], reds=["frame"], virtualizables=["frame"],
-                      get_printable_location=get_location)
+                      get_printable_location=get_location, is_recursive=True)
 
 
 @elidable
```

**Comment by cgore** [comment]
I don't see how my change would surface that?
I'm a bit confused by what the JitDriver is doing honestly.

**Comment by heyLu** [comment]
That's because travis pulls in pypy every time it runs a build.  Your PR just happened to be the first one that pulled in that change.  This is happening for all PRs now...

**Comment by heyLu** [comment]
Thanks!

**Pull request merged**
