### PR TITLE
adds promotion to bigint on overflow

### LINKED ISSUE #58: Integer overflow handling
Currently in pixie and integer is an integer, and a big integer is a big integer...

Is Pixie planned to have transparent promotion to arbitrary precision integers like python? or is it going  to throw an exception on overflow like clojure seems to. 

Personally I think the python method is quite nice and "just works" - Really just a language design question.

### PR DESCRIPTION
**Pull request by thomasmulvaney**
This should fix #58

### CODE REVIEW

**Comment by andrewchambers** [comment]
cool!

**Comment by thomasmulvaney** [comment]
Unfortunately it looks like compile_tests fails at the moment because pxic_writer doesn't support BigIntegers. Will try and fix that.

**Comment by MatthewWest** [comment]
Can this be merged now? I'm going through old issues to see what I can help resolve, and this looks like it could be merged.

**Comment by heyLu** [comment]
Yes, we can merge this, but I don't want to decide this on my own.

@halgari Can you have a look at this?

**Comment by thomasmulvaney** [comment]
Cheers, I'm going to open up writing BigIntegers (non string format) as an issue so it doesn't go forgotten..

**Pull request merged**
