### PR TITLE
add cycle

### PR DESCRIPTION
**Pull request by stuarth**

### CODE REVIEW

**Comment by heyLu** [comment]
Thanks!  Happy holiday!  :christmas_tree:

**Comment by heyLu** [comment]
Can you amend this commit and then force push?  Travis didn't seem to pick it up...

(Happy holiday!  :christmas_tree:)

**Comment by stuarth** [comment]
@heyLu no problem! Happy holidays :smile:

**Comment by heyLu** [comment]
Thanks!

**Pull request merged**
