### PR TITLE
Better reader

### LINKED ISSUE #217: Crashes when reading files with unmatched delimiters
Running load-file on a file that contains only one of the characters `([{` will cause a RPython error and a call to `abort`. The same thing happens when running `pixie-vm`:
```
$ echo '(' > foo.pxi
$ pixie-vm
Pixie 0.1 - Interactive REPL
(linux, gcc)
:exit-repl or Ctrl-D to quit
----------------------------
user => (load-file "foo.pxi")
RPython traceback:
  File "implement.c", line 1321, in entry_point
  File "implement.c", line 13122, in ReplFn_inner_invoke
  File "rpython_jit_metainterp_warmspot.c", line 854, in ll_portal_runner__Unsigned_Unsigned_Signed_listP
  File "pixie_vm_interpreter.c", line 3592, in portal_2
  File "pixie_vm_code.c", line 25207, in Wload_file_wrapped_fn
  File "pixie_vm_stdlib.c", line 3044, in _load_file
  File "pixie_vm_code.c", line 11254, in Wload_reader_wrapped_fn
  File "pixie_vm_stdlib.c", line 10190, in load_reader
  File "pixie_vm_reader.c", line 1744, in read
  File "pixie_vm_reader.c", line 14534, in ListReader_invoke
  File "pixie_vm_reader.c", line 2718, in eat_whitespace
  File "pixie_vm_reader.c", line 3491, in MetaDataReader_read
Fatal RPython error: EOFError
Aborted (core dumped)
$ pixie-vm foo.pxi
[similar traceback snipped]
Aborted (core dumped)
```

`")]\` will work fine in the REPL (i.e. throw an exception without crashing), but cause segfaults when running `pixie-vm`:
```
$ echo '"' > foo.pxi && pixie-vm foo.pxi
Segmentation fault (core dumped)
```

`}` works for both the REPL and `pixie-vm`.

I tested this with commit 7be556ee6b04437151745eeaf8c24227d1274a2e on a 64-bit Arch Linux machine.

### PR DESCRIPTION
**Pull request by thomasmulvaney**
This should fix #217 

Also makes errors for arities a bit nicer by sorting arities in ascending order.

### CODE REVIEW

**Comment by halgari** [comment]
Build passed (even though there was a race condition in the test). Failure is a known issue, merging. 

Thanks!

**Comment by justinj** [comment]
Hey, as a heads up, this reintroduces the bug fixed in #224.

Here's a failing test case:
```
(t/assert= (read-string "(foo ; bar\n)") '(foo))
```

**Comment by thomasmulvaney** [comment]
Thanks for spotting that! I'll add some line comment test cases to `test-reader.pxi` and try and get them passing.

**Comment by thomasmulvaney** [comment]
Ok so it looks like I didn't fetch from upstream, messed up a rebase, or just made a boo boo as I've clearly rm'd some important changes from reader you made. I'll stick these back in shortly - Sorry!

**Comment by justinj** [comment]
No worries! I'll be glad to have these error messages.

**Pull request merged**
