### PR TITLE
Adds an evironment associative structure

### PR DESCRIPTION
**Pull request by thomasmulvaney**
The environment stuff is namespaced to `pixie.stdlib` perhaps I should put it under something else though?

### CODE REVIEW

**Comment by heyLu** [comment]
I think you could do this entirely in pixie by now, using the `getenv` and `setenv` (or `putenv`) from libc.

**Comment by thomasmulvaney** [comment]
You could get and set via `getenv` and `setenv`, but are you able to get a list of all env vars using libc? I also thought some of the functionality might be useful from with in the rpython code.

**Comment by pmonks** [comment]
Looks like this guy might have it: https://bitbucket.org/pypy/pypy/src/default/rpython/rtyper/module/ll_os_environ.py

**Comment by heyLu** [comment]
Ah right, there *is* `man 7 environ`, but I don't know if our FFI can handle it yet. (It's a `**char`. We'd also have to do the key/value splitting ourselves.)

**Comment by thomasmulvaney** [comment]
@pmonks the call to `os.environ.list()` just wraps around the code you linked to. `os.environ` is actually just a constant in rpython and the dict lookups i'm making are really translated to the calls in that link.

**Comment by heyLu** [comment]
@thomasmulvaney I don't know, maybe ask tbaldridge about it on IRC? (I tried using `pixie.ffi-infer/defconst`, but it only seems to work for integers, not `**char`.)

**Comment by halgari** [comment]
#241 should help here. And yes, it would be nice to keep this in pixie code.

**Comment by halgari** [comment]
This branch can't merge cleanly with master. If someone could update it, I'll merge it.

**Comment by thomasmulvaney** [comment]
I've rebased it. Seems to be the usual failure on Travis. Env should probably be made a global mutable object perhaps and using the mentioned FFI stuff would be ideal too but haven't had a chance to dig into that much.

**Pull request merged**
