### PR TITLE
#319 Add a reasonable error message if boost is not found

### PR DESCRIPTION
**Pull request by MatthewWest**
This is a bit of a hack implementation, I know—what should really happen is that we should switch to using autoconf and automake to check dependencies and generate build targets. Essentially it just checks two common include directories: `/usr/local/include` and `/usr/include` for the boost folder, and if it isn't there, it refuses to compile and prints a message that Boost is not found. This addresses #319 

I also updated the Readme a bit—the current size of the executable is 10.3 MB, so I updated that. Also, I used `;;` for the comments rather than `(comment ...)`.

### CODE REVIEW

**Comment by MatthewWest** [comment]
Added a commit to encode BigIntegers natively in compiled code (mostly copied the implementation for Integers).

**Comment by andrewchambers** [comment]
Just a note, there is no good reason to use autotools or automake ever. Especially in a project like this. A python script it all that is needed and can be assumed to exist on every OS we support.

**Comment by MatthewWest** [comment]
Bigintegers implemented #345

**Comment by MatthewWest** [comment]
@andrewchambers I haven't seen a good example of a python script as a build script. Can you point me to an example?

**Comment by andrewchambers** [comment]
Pixie does not have a complicated or incremental build, Autotools are a big mess of unnecessary complexity here.

If I have time I will try work a prototype.

**Comment by heyLu** [comment]
Thanks, @MatthewWest!

**Pull request merged**
