### PR TITLE
Added mkdtmp to stdlib

### PR DESCRIPTION
**Pull request by oholiab**
This is just a copy of the same def in ffi-infer, just seems like it should be in stdlib (and I want to use it ;) )

### CODE REVIEW

**Comment by oholiab** [comment]
Also just added rmdir as one is not so helpful without the other

**Comment by heyLu** [comment]
Thanks!  Can you add `mkdir` as well?  :)

**Comment by oholiab** [comment]
Sure :)

**Comment by oholiab** [comment]
I added rm whilst I was at it seeing as I need that too ;)

**Comment by thomasmulvaney** [comment]
Merged :sparkles:

**Pull request merged**
