### PR TITLE
fix first on Seqables

### LINKED ISSUE #376: (first {:some :map}) throws RuntimeException
It seems as though `(first {:some :map})` is intended to fall down to https://github.com/pixie-lang/pixie/blob/master/pixie/vm/stdlib.py#L135 which would be similar (equivalent?) to `(first (seq {:some :map}))`

This is the 

```clj
user => (first {:some :map})
ERROR: 
 in pixie function repl_fn

in /home/bja/code/pixie/pixie/repl.pxi at 24:24
               (let [x (eval form)]
                       ^
in internal function eval

in <unknown> at 2:1
(first {:some :map})
^
in pixie function first

in /home/bja/code/pixie/pixie/stdlib.pxi at 689:5
    (-first coll)))
    ^
in polymorphic function -first dispatching on pixie.stdlib.PersistentHashMap

RuntimeException: :pixie.stdlib/AssertionException No override for pixie.stdlib.PersistentHashMap on -first in protocol ISeq
```

### PR DESCRIPTION
**Pull request by thomasmulvaney**
Fixes #376

### CODE REVIEW

**Comment by emidln** [comment]
Does this need to extend to second, third, and fourth as well?

**Comment by thomasmulvaney** [comment]
Good point. I also realized that its possible to make them all work. In pixie a protocol can extend another protocol. So I've just said that ISeq extends ISeqable.

**Comment by heyLu** [comment]
Looks good!  Can you add a test for a non-empty map as well?

**Comment by thomasmulvaney** [comment]
Done. This required getting MapEntry equality sorted too.

**Comment by heyLu** [comment]
Thanks!

**Pull request merged**
