### PR TITLE
Added letfn macro to the stdlib.

### PR DESCRIPTION
**Pull request by egregius313**
I find I regularly use the letfn macro and think the most important place for it is the stdlib.

### CODE REVIEW

**Comment by thomasmulvaney** [comment]
Nice. Just needs a test please.

**Comment by egregius313** [comment]
No problem. This is my first PR on a project though, so where should I put the test?

**Comment by thomasmulvaney** [comment]
In `tests/pixie/test-stdlib.pxi` would be great.

**Comment by heyLu** [comment]
Merged #534 in place of this.  It has the letfn macros and tests.

**Pull request closed without merging**
