### PR TITLE
add pixie.walk

### PR DESCRIPTION
**Pull request by mpenet**
It's very similar to clojure.walk but uses transients when possible, and is extensible via a protocol.

### CODE REVIEW

**Comment by thomasmulvaney** [comment]
I've restarted the build as it looks like pulling down deps failed.

**Comment by mpenet** [comment]
yep, the pypy archive is not available https://bitbucket.org/pypy/pypy/get/default.tar.bz2 returns an http 500 at the moment.

**Comment by mpenet** [comment]
I forgot to mention, this API doesn't include the "outer" fn parameter from the clojure equivalent, I never really understood why they baked in this fn, as you can just call it on the result returned by a walk yourself and seems to make things more confusing for little benefit. 

Feel free to tell me if you think it's not ok.

**Comment by thomasmulvaney** [comment]
I agree that the outer is probably not necessary. I like the choice of an `IWalk` protocol so walking can be extended in the future.

**Comment by mpenet** [comment]
Do you need me to modify anything on this?  (I need it for a toy project, but worst case I can use a local fork).

**Comment by thomasmulvaney** [comment]
A quick squash would be nice, but otherwise this looks great. Thanks!

**Comment by mpenet** [comment]
There you go! Squashed.

**Comment by heyLu** [comment]
Thanks!

**Pull request merged**
