### PR TITLE
Refactor io

### PR DESCRIPTION
**Pull request by thomasmulvaney**

### CODE REVIEW

**Comment by justinj** [comment]
I might be doing something wrong, but I'm having trouble running the tests after this. I think there's a circular dependency from `io-common -> uv -> ffi-infer -> io-blocking -> io-common`.

**Comment by thomasmulvaney** [comment]
The tests all seemed to pass for me. Have you done a `make clean_pxi` then `make compile_src`?

**Comment by justinj** [comment]
Hm, if I `make compile_src` first then they pass, but not otherwise. Is that expected of `pxic`s?

**Comment by thomasmulvaney** [comment]
So if I'm following correctly, doing a `make clean_pxi` and then calling `make run_interactive_tests` fails?

**Comment by justinj** [comment]
`make run_built_tests` fails with something like this:
```
in pixie function cb-stream-writer

in /Users/justin/dev/repos/pixie/pixie/io/common.pxi at 47:21
          uv_write (uv/uv_write_t)]
                    ^
RuntimeException: :pixie.stdlib/AssertionException Var uv_write_t is undefined
```

`make run_interpreted_tests` seems to run for a while and then fail.

Everything seems to work at ea20df6.

**Comment by thomasmulvaney** [comment]
Thanks, I can confirm that this occurs for me too when I rm the `pxic` files. I'm not sure what's going on exactly. But will dig into it a bit tonight.

**Comment by justinj** [comment]
Cool, thanks!

**Comment by thomasmulvaney** [comment]
I can compile just io/common.pxi and get the tests to run with out errors. That seems to be the minimum amount of compilation required to make things work. The question is why... I don't see any circular dependencies so I don't think that's the issue. Very curious indeed.

**Pull request merged**
