### PR TITLE
Implement fs/size and fs/permissions

### PR DESCRIPTION
**Pull request by justinj**

### CODE REVIEW

**Comment by heyLu** [comment]
Can you try doing it via the FFI? It should be possible, here's a related example that also returns a struct: https://github.com/pixie-lang/pixie/blob/master/pixie/ffi-infer.pxi#L306-L321

**Comment by justinj** [comment]
Ok, I'll look into that. Looks like I'll need to come up with a test that will work on Travis too.

**Comment by justinj** [comment]
I'm having some difficulty getting this to work with FFI across both OSX and Linux, would someone be willing to look at this with me over IRC sometime?

**Comment by halgari** [comment]
I think the problem here is how you are including c, the name libc is not the same on linux and osx. But probably we should just implement permissions via libuv. That way they are a) async, b) cross-platform. If you want to look into that, it shouldn't be that hard to copy what is in `pixie.io` and just change a few function names. Otherwise, if you don't think you'll have the time, I'll try to take care of it soon. 

Let me know either way so that we don't duplicate work.

**Comment by justinj** [comment]
Ah I see, I didn't realize libc wasn't the same across linux and osx. I should be able to do it later this weekend (Sunday, probably), but if you'd like to do it sooner than that feel free.

**Comment by justinj** [comment]
Ok, let me know how that looks. `defuvfsfn` is neat, by the way.

**Comment by halgari** [comment]
Looks good, thanks!

**Pull request merged**
