### PR TITLE
fn pre and post conditions

### PR DESCRIPTION
**Pull request by stuarth**
pre and post conditions in the same style as Clojure

### CODE REVIEW

**Comment by thomasmulvaney** [comment]
Perhaps the build has failed because pypy has changed?

**Comment by thomasmulvaney** [comment]
I restarted the build and it's all green now. Must have pulled down a bad pypy build.

**Comment by stuarth** [comment]
thanks for that @thomasmulvaney

**Comment by thomasmulvaney** [comment]
@stuarth this would be really cool to get in. My only suggestion is that the assertions perhaps don't throw enough information as to where the error happened. Perhaps adding a message to the assertion such as "in precondition (even? x)" might be handy for debugging?

**Comment by arrdem** [comment]
A possibility worth exploring... you could easily extend the pre/post vector grammar to be `(list string?)*` where the string following a predicate sexpr is interpreted to be the error message to be thrown should that guard fail. This is an improvement to Clojure's pre/post I've kicked around before.

**Comment by heyLu** [comment]
This looks good, I'll merge this later today if nobody complains.

**Comment by heyLu** [comment]
Thanks @stuarth! :sparkles:

**Pull request merged**
